### ISSUE TITLE
Installation fails as pip is not installed in the boot node

### ISSUE THREAD

**Issue by patrocinio** [hassenius/terraform-icp-softlayer#3]

**Comment by hassenius** [comment]
Hi Patricio,

Thanks for reaching out. Are you able to provide the output of the /tmp/prereqs.log file on the relevant servers?
Pip is expected to get installed as part of the prerequisites script in the icp-deploy module.

https://github.com/ibm-cloud-architecture/terraform-module-icp-deploy/blob/master/scripts/common/prereqs.sh#L34
for apt based systems

https://github.com/ibm-cloud-architecture/terraform-module-icp-deploy/blob/master/scripts/common/prereqs.sh#L58
for yum based systems.

**Comment by hassenius** [comment]
unreproducable. Most likely local SSH issue
